[theme]
base = "light"
primaryColor = "#0078D4"
backgroundColor = "#F5F6F8"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#323130"
font = "sans serif"

[server]
headless = true
enableXsrfProtection = true

[browser]
gatherUsageStats = false
